fix: use hourCycle for Intl.DateTimeFormats
muan/site pull request #48
Opened 2023-12-09 04:34 UTC by 0xdhrv

## Summary

- This fixes the regex replace for 24:00 issue using hour cycle 

### References
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#hourcycle
- https://github.com/muan/site/blob/a07a84bffd8105fe350791991f24d1f9149f9d4f/assets/site.js#L5-L15C29

2023-12-14 21:39 UTC, 0xdhrv commented
@muan if can review this

2024-06-06 06:58 UTC, muan requested changes
Sorry for the huge delay! I remember seeing this but it slipped through the cracks. Just one requested change. Thank you!

2024-06-06 06:58 UTC, muan commented on assets/site.js
> +    hourCycle: "h23"
```suggestion
    hour12: false
```

According to MDN,

> When true, this option sets hourCycle to either "h11" or "h12", depending on the locale. _When false, it sets hourCycle to "h23"._

2024-06-09 05:21 UTC, muan approved these changes

2024-06-09 05:21 UTC, muan commented
Thank you!

2024-06-09 05:21 UTC, merged